import React from 'react';
import { BRAND } from '../translations.js';
import { useLanguage } from '../context/LanguageContext.jsx';

/**
 * Brand lockup: language-aware wordmark + optional hairline & specialism line.
 *
 * The four wordmark files in /public are generated by scripts/process-logo.mjs
 * (transparent, tightly trimmed):
 *   logo-en-light / logo-ar-light  -> near-black ink, for light surfaces
 *   logo-en-dark  / logo-ar-dark   -> white ink, for dark surfaces
 */
export default function BrandLogo({
  dark = false,
  tagline = false,
  className = '',
  alt = '',
  language,
}) {
  const { lang: currentLanguage } = useLanguage();
  const lang = language || currentLanguage;
  const isAr = lang === 'ar';
  const src = `/logo-${isAr ? 'ar' : 'en'}-${dark ? 'dark' : 'light'}.png`;
  const name = isAr ? BRAND.nameAr : BRAND.nameEn;

  return (
    <span
      className={`brand-lockup ${dark ? 'lockup-dark' : 'lockup-light'} ${className}`.trim()}
    >
      <img
        src={src}
        alt={alt || name}
        className="brand-wordmark"
        width="760"
        height={isAr ? 125 : 69}
        decoding="async"
      />

      {tagline && (
        <span className="brand-tagline" aria-hidden="true">
          <span className="brand-tagline-rule" />
          <span className="brand-tagline-text">
            {isAr ? BRAND.taglineAr : BRAND.taglineEn}
          </span>
        </span>
      )}
    </span>
  );
}
