import { BRAND, waLink, T } from './translations.js';

export { BRAND, waLink, T };

export const NAV_LINKS = [
  { id: 'home', path: '/' },
  { id: 'services', path: '/services' },
  { id: 'checker', path: '/services#checker' },
  { id: 'gallery', path: '/gallery' },
  { id: 'videos', path: '/gallery#videos' },
  { id: 'reviews', path: '/reviews' },
  { id: 'faq', path: '/reviews#faq' },
  { id: 'contact', path: '/contact' },
];

export const GALLERY_ITEMS = [
  {
    id: 'washer-workshop',
    src: 'gal-washer-department',
    category: 'washer',
    titleAr: 'ورشة صيانة الغسالات الأوتوماتيكية',
    titleEn: 'Automatic Washing Machine Repair Department',
  },

  {
    id: 'storefront-day',
    src: 'gal-showroom-workshop',
    category: 'workshop',
    titleAr: 'واجهة ومقر مؤسسة جوزاء للتبريد والتكييف بالرياض',
    titleEn: 'Official Jawzaa Storefront & Service Center in Riyadh',
  },
  {
    id: 'storefront-signage',
    src: 'gal-storefront-signage',
    category: 'workshop',
    titleAr: 'لوحة وهوية مؤسسة جوزاء الرسمية بالرياض',
    titleEn: 'Official Jawzaa Storefront Signage in Riyadh',
  },
  {
    id: 'workshop-technician',
    src: 'gal-tech-split-ac',
    category: 'ac',
    titleAr: 'فني تكييف يقوم بفحص وصيانة وحدة سبليت',
    titleEn: 'HVAC Technician Inspecting & Servicing Split Unit',
  },
  {
    id: 'ac-units-wall',
    src: 'gal-ac-display-bay',
    category: 'ac',
    titleAr: 'وحدات تكييف سبليت مجهزة للتركيب والصيانة',
    titleEn: 'Split Air Conditioners Display & Service Bay',
  },
  {
    id: 'ac-outdoor-stack',
    src: 'gal-outdoor-condensers',
    category: 'ac',
    titleAr: 'وحدات مكيفات خارجية بعد الصيانة والتنظيف',
    titleEn: 'Outdoor AC Condenser Units Serviced & Ready',
  },
  {
    id: 'window-ac-repair',
    src: 'gal-window-ac-repair',
    category: 'ac',
    titleAr: 'صيانة وفحص مكيفات الشباك بالورشة',
    titleEn: 'Window AC Unit Troubleshooting in Workshop',
  },
  {
    id: 'fridge-bay',
    src: 'gal-fridge-repair-bay',
    category: 'fridge',
    titleAr: 'قسم صيانة الثلاجات والفريزرات المنزلية',
    titleEn: 'Home Refrigerator & Freezer Repair Bay',
  },
  {
    id: 'fridge-repair',
    src: 'gal-refrigeration-circuit',
    category: 'fridge',
    titleAr: 'فحص دورة التبريد والكمبروسر للثلاجات',
    titleEn: 'Compressor & Refrigeration Circuit Diagnostics',
  },
  {
    id: 'hvac-display',
    src: 'gal-spare-parts-hvac',
    category: 'workshop',
    titleAr: 'قسم قطع الغيار والمحركات الكهربائية',
    titleEn: 'Spare Parts, Motors & HVAC Equipment Section',
  },
  {
    id: 'storefront-open',
    src: 'gal-customer-reception',
    category: 'workshop',
    titleAr: 'استقبال العملاء في معرض جوزاء بالرياض',
    titleEn: 'Customer Reception at Jawzaa Showroom',
  },
  {
    id: 'storefront-street',
    src: 'gal-main-facility',
    category: 'workshop',
    titleAr: 'موقع مؤسسة جوزاء بالشارع العام',
    titleEn: 'Jawzaa Main Facility & Service Center',
  },
];

export const VIDEO_ITEMS = [
  {
    id: 'video-1',
    src: '/videos/jawzaa-work-01.mp4',
    poster: '/videos/poster-1.jpg',
    titleAr: 'فحص واختبار وحدة تكييف سبليت بعد الصيانة',
    titleEn: 'Inspection & Load Testing of Split AC Unit',
    duration: '0:15',
    categoryAr: 'صيانة مكيفات',
    categoryEn: 'AC Service',
  },
  {
    id: 'video-2',
    src: '/videos/jawzaa-work-02.mp4',
    poster: '/videos/poster-2.jpg',
    titleAr: 'صيانة وشحن فريون لكمبروسر ثلاجة',
    titleEn: 'Refrigerator Compressor Repair & Freon Gas Refill',
    duration: '0:20',
    categoryAr: 'تصليح ثلاجات',
    categoryEn: 'Refrigerator Repair',
  },
  {
    id: 'video-3',
    src: '/videos/jawzaa-work-03.mp4',
    poster: '/videos/poster-3.jpg',
    titleAr: 'عملية لف وإعادة بناء محرك تكييف بنحاس نقي',
    titleEn: 'Electric Motor Rewinding with Pure Copper Wire',
    duration: '0:35',
    categoryAr: 'لف موتورات',
    categoryEn: 'Motor Rewind',
  },
  {
    id: 'video-4',
    src: '/videos/jawzaa-work-04.mp4',
    poster: '/videos/poster-4.jpg',
    titleAr: 'التشغيل النهائي واختبار ضغط التبريد',
    titleEn: 'Final Operational Testing & Pressure Verification',
    duration: '0:25',
    categoryAr: 'فحص جودة',
    categoryEn: 'Quality Check',
  },
];

export const POSTER_ITEMS = [
  {
    src: 'poster-clean-filter',
    titleAr: 'أهمية تنظيف وغسيل فلاتر المكيف بانتظام',
    titleEn: 'Importance of Regular AC Filter Cleaning',
  },
  {
    src: 'poster-correct-diagnosis',
    titleAr: 'التشخيص الدقيق يوفر تكلفة تغيير القطع غير التالفة',
    titleEn: 'Precise Diagnosis Saves Unnecessary Parts Cost',
  },
  {
    src: 'poster-4-warning-signs',
    titleAr: '4 علامات تحذيرية تدل على حاجة المكيف لصيانة عاجلة',
    titleEn: '4 Warning Signs Your AC Needs Urgent Service',
  },
  {
    src: 'poster-ac-not-cooling',
    titleAr: 'أسباب ضعف التبريد في فصل الصيف بالرياض',
    titleEn: 'Causes of AC Cooling Weakness in Riyadh Summer',
  },
  {
    src: 'poster-motor-rewinding',
    titleAr: 'إعادة لف المحركات بنحاس معزول حرارياً',
    titleEn: 'Motor Rewinding with Heat-Insulated Copper',
  },
  {
    src: 'poster-fridge-door-seal',
    titleAr: 'كيف تحافظ حشوة باب الثلاجة على برودة الأطعمة',
    titleEn: 'How Refrigerator Door Gaskets Preserve Cold Air',
  },
];

export const TESTIMONIALS_DATA = [
  {
    id: 5,
    nameAr: 'أبو عبدالعزيز الزهراني',
    nameEn: 'Abu Abdulaziz Al-Zahrani',
    areaAr: 'حي الشفا — الرياض',
    areaEn: 'Al-Shifa District — Riyadh',
    rating: 5,
    date: '2026',
    serviceAr: 'صيانة غسالة إل جي أوتوماتيك',
    serviceEn: 'LG Automatic Washer Repair',
    textAr: 'الغسالة كانت تصدر صوت خبط قوي وتوقف عند مرحلة التجفيف. اتصلت فيهم وجاء الفني وفكها وفحص المساعدات ورولمان البلي وغيرهم بقطع أصلية. الحين هادية جداً حتى في أعلى سرعة عصر. أنصح بالتعامل معهم بشدة.',
    textEn: 'The washing machine made heavy banging noises and stopped before spinning. The technician inspected the suspension shocks and drum bearings, replacing them with OEM parts. Now it runs super quiet even on maximum spin speed.',
  },

  {
    id: 1,
    nameAr: 'عبدالله المطيري',
    nameEn: 'Abdullah Al-Mutairi',
    areaAr: 'حي الياسمين — الرياض',
    areaEn: 'Al-Yasmin District — Riyadh',
    rating: 5,
    date: '2026',
    serviceAr: 'صيانة وشحن فريون مكيف سبليت',
    serviceEn: 'Split AC Service & Freon Recharge',
    textAr: 'المكيف كان يشتغل بدون تبريد في عز الظهر، تواصلت معهم وجاني الفني بنفس اليوم مع أجهزة قياس حديثة. طلع الفريون ناقص وفيه تنسيم خفيف في الصامولة، صلحوه وشحنوا فريون أصلي ورجع التبريد ثلج. تعامل راقي وأسعار واضحة بدون لف ودوران.',
    textEn: 'My AC was running without cooling during midday heat. I contacted Jawzaa and the technician arrived the same day with digital gauges. He found a minor flare nut leak, fixed it, and recharged genuine freon. The cooling is icy cold now. Extremely professional and upfront pricing.',
  },
  {
    id: 2,
    nameAr: 'أم فهد العتيبي',
    nameEn: 'Um Fahad Al-Otaibi',
    areaAr: 'حي النرجس — الرياض',
    areaEn: 'Al-Narjis District — Riyadh',
    rating: 5,
    date: '2026',
    serviceAr: 'تصليح ثلاجة سامسونج نوفروست',
    serviceEn: 'Samsung No-Frost Refrigerator Repair',
    textAr: 'الثلاجة كانت تنقط مياه من الداخل والمؤونة بدأت تتلف، الفني فحصها قدامي واكتشف انسداد مجرى إذابة الثلج وتلف حساس السخان. بدلوه بقطعة أصلية ونظفوا المكان وراهم وأعطوني كرت ضمان. شغل نظيف جداً ويستاهلون كل خير.',
    textEn: 'Our fridge was leaking water inside and food was spoiling. The technician tested the defrost circuit in front of me and replaced the faulty sensor with an original part. He even cleaned up afterward and gave a written warranty. Very clean and trustworthy work.',
  },
  {
    id: 3,
    nameAr: 'م. خالد الدوسري',
    nameEn: 'Eng. Khalid Al-Dosari',
    areaAr: 'حي الروضة — الرياض',
    areaEn: 'Al-Rawdah District — Riyadh',
    rating: 5,
    date: '2026',
    serviceAr: 'لف موتور مروحة مكيف مركزي',
    serviceEn: 'Central AC Blower Motor Rewinding',
    textAr: 'مركان موتور المكيف احترق وكانت رائحة الحريق واصلة لكل البيت. أخذوه للورشة وأعادوا لفه بسلك نحاس نقي وضبطوا البيرنجات. رجعوه وشغلوه وقاسوا الأمبيرات قدامي، شغال هادي وممتاز ودرجة حرارته طبيعية تماماً. شغل مهندسين حقيقي.',
    textEn: 'The AC blower motor burned out and smelled bad. They took it to their workshop, rewound it with pure copper wire, and replaced the bearings. They reinstalled and amp-tested it right in front of me. Runs quiet and cool. Outstanding engineering craftsmanship.',
  },
  {
    id: 4,
    nameAr: 'سارة القحطاني',
    nameEn: 'Sarah Al-Qahtani',
    areaAr: 'حي قرطبة — الرياض',
    areaEn: 'Qurtubah District — Riyadh',
    rating: 5,
    date: '2026',
    serviceAr: 'عقد صيانة وغسيل سنوي للمكيفات',
    serviceEn: 'Annual AC Cleaning & Service Contract',
    textAr: 'أخذت معهم عقد صيانة لفيلا كاملة تشمل غسيل 7 مكيفات سبليت. جاء فريق فني منظم ومعهم أغطية حماية للجدران والأثاث وما نقطت قطرة ماء واحدة على الأرض. المكيفات فرقت بالصوت وقوة دفع الهواء والتبريد بشكل ملحوظ.',
    textEn: 'We signed an annual maintenance contract for our whole villa including 7 split units. The crew arrived with wall and furniture protection covers — not a single drop on the floor. The airflow, cooling, and quietness improved remarkably.',
  },
  {
    id: 6,
    nameAr: 'فيصل الشمري',
    nameEn: 'Faisal Al-Shammari',
    areaAr: 'حي الملقا — الرياض',
    areaEn: 'Al-Malqa District — Riyadh',
    rating: 5,
    date: '2026',
    serviceAr: 'صيانة طارئة لمكيف مخفي (كونسيلد)',
    serviceEn: 'Concealed Ducted AC Emergency Repair',
    textAr: 'خدمة سريعة جداً. المكيف توقف في عطلة نهاية الأسبوع وفي حر شديد، تواصلت عبر واتساب وردوا خلال دقيقتين ووصل الفني خلال ساعة وحل مشكلة لوحة التحكم والكابستور. شكراً لاهتمامكم ومصداقيتكم.',
    textEn: 'Remarkably fast response. Our ducted AC shut down during the weekend in intense heat. I texted on WhatsApp, got a reply in 2 minutes, and the technician arrived within an hour to fix the control board and capacitor. Highly recommended!',
  },
];

export const FAQS_DATA = [
  {"qEn":"Do you repair washing machines and dryers in Riyadh?","qAr":"هل تصلحون الغسالات والنشافات في الرياض؟","aEn":"Yes. We diagnose and repair automatic washing machines and dryers, including drainage, spin-cycle, door-lock and control-board faults. Share the brand, model and symptoms when booking.","aAr":"نعم، نفحص ونصلح الغسالات الأوتوماتيكية والنشافات، بما في ذلك التصريف والعصر وقفل الباب ولوحة التحكم. أرسل الماركة والموديل ووصف العطل عند الحجز."},
  {"qEn":"Can my washing machine be repaired at home?","qAr":"هل يمكن إصلاح الغسالة في المنزل؟","aEn":"Many faults can be inspected and repaired on site. Bearing, drum or major electronic repairs may need workshop service; the technician explains the options and quote before work begins.","aAr":"يمكن فحص وإصلاح كثير من الأعطال في المنزل. قد تتطلب أعمال البلي أو الحلة أو الإلكترونيات نقل الجهاز للورشة، ويوضح الفني الخيارات والتكلفة قبل البدء."},
  {"qEn":"What should I do if my washing machine leaks or stops draining?","qAr":"ماذا أفعل إذا سربت الغسالة الماء أو توقفت عن التصريف؟","aEn":"Stop the cycle and turn off the water supply. If safe and dry, disconnect the power. Avoid restarting the machine and send us the model and a description of the fault to arrange an inspection.","aAr":"أوقف البرنامج وأغلق مصدر الماء. افصل الكهرباء إذا كان المكان جافاً وآمناً. تجنب إعادة التشغيل وأرسل الموديل ووصف العطل لترتيب الفحص."},
  {
    qAr: 'هل تقدمون خدمة الصيانة المنزلية في جميع أحياء مدينة الرياض؟',
    qEn: 'Do you provide home repair service across all neighborhoods in Riyadh?',
    aAr: 'نعم، نغطي كافة مناطق وأحياء الرياض (شمال، شرق، غرب، وجنوب الرياض) مثل النرجس، الياسمين، الملقا، الروضة، قرطبة، العليا، السويدي، الشفا، الحمراء، وغيرها مع إمكانية الوصول في نفس اليوم.',
    aEn: 'Yes, we cover all areas of Riyadh (North, East, West, and South) including Al-Narjis, Al-Yasmin, Al-Malqa, Al-Rawdah, Qurtubah, Olaya, Al-Suwaidi, Al-Shifa, Al-Hamra, and more with same-day service.',
  },
  {
    qAr: 'كم يستغرق فحص وتنظيف المكيف أو تصليح الثلاجة؟',
    qEn: 'How long does AC cleaning/service or refrigerator repair take?',
    aAr: 'غسيل وصيانة المكيف السبليت تستغرق عادة من 35 إلى 50 دقيقة لكل مكيف، أما تصليح أعطال الثلاجات والفريزرات فغالباً يكتمل خلال 45 إلى 90 دقيقة في نفس الزيارة ما لم يتطلب الأمر نقله للورشة.',
    aEn: 'Deep cleaning and servicing a split AC typically takes 35 to 50 minutes per unit. Most refrigerator and freezer repairs are completed within 45 to 90 minutes during the same visit.',
  },
  {
    qAr: 'هل تقدمون ضماناً معتمداً على عمليات الصيانة وقطع الغيار؟',
    qEn: 'Do you offer an official warranty on repairs and replacement parts?',
    aAr: 'بالتأكيد، نمنحك سند ضمان خطي معتمد على جميع قطع الغيار المستبدلة والخدمة المقدمة. في حال تكرار نفس العطل خلال فترة الضمان، نعود إليك ونصلحه مجاناً دون أي تكلفة إضافية.',
    aEn: 'Absolutely. We provide a written warranty covering both the installed spare parts and labor. If the same malfunction reoccurs within the warranty period, we return and service it at zero extra cost.',
  },
  {
    qAr: 'كيف تتم عملية التسعير وهل توجد رسوم خفية؟',
    qEn: 'How is pricing determined, and are there any hidden fees?',
    aAr: 'نعتمد مبدأ الشفافية الكاملة؛ يقوم الفني بفحص الجهاز بالأجهزة الحديثة ويحدد سبب العطل والتكلفة الإجمالية بدقة ويشرحها لك قبل البدء، ولن يتم تنفيذ أي عمل إلا بعد موافقتك الصريحة.',
    aEn: 'We operate with 100% transparency. Our technician diagnoses the appliance with digital tools, provides a fixed upfront quote, and explains the repair scope before beginning. No work starts without your approval.',
  },
  {
    qAr: 'هل تستخدمون قطع غيار أصلية ومضمونة؟',
    qEn: 'Do you use 100% genuine and certified spare parts?',
    aAr: 'نعم، نحن نوفر فقط قطع الغيار الأصلية المعتمدة من الوكلاء المعتمدين والمطابقة لمواصفات الشركة المصنعة لضمان أفضل أداء وعمر تشغيلي طويل لجهازك.',
    aEn: 'Yes, we strictly supply genuine manufacturer-certified spare parts sourced from authorized distributors to guarantee peak performance and extended appliance lifespan.',
  },
  {
    qAr: 'ما هي أسرع طريقة لحجز فني صيانة الآن؟',
    qEn: 'What is the fastest way to book a service technician now?',
    aAr: 'أسرع طريقة هي الضغط على زر الواتساب في الموقع لإرسال طلبك فوراً، أو الاتصال المباشر على رقمنا الموحد 0544786559 وسيقوم فريقنا بتنسيق الموعد في أقل من 5 دقائق.',
    aEn: 'The fastest method is tapping the WhatsApp button on our website for an instant service chat, or calling our direct hotline 0544786559. Our service team confirms bookings within 5 minutes.',
  },
];

export const RIYADH_AREAS = [
  { ar: 'العليا', en: 'Al-Olaya' },
  { ar: 'النرجس', en: 'Al-Narjis' },
  { ar: 'الياسمين', en: 'Al-Yasmin' },
  { ar: 'الملقا', en: 'Al-Malqa' },
  { ar: 'حطين', en: 'Hittin' },
  { ar: 'الصحافة', en: 'Al-Sahafah' },
  { ar: 'الروضة', en: 'Al-Rawdah' },
  { ar: 'قرطبة', en: 'Qurtubah' },
  { ar: 'اليرموك', en: 'Al-Yarmouk' },
  { ar: 'الحمراء', en: 'Al-Hamra' },
  { ar: 'المروج', en: 'Al-Murooj' },
  { ar: 'العقيق', en: 'Al-Aqiq' },
  { ar: 'السويدي', en: 'Al-Suwaidi' },
  { ar: 'الشفا', en: 'Al-Shifa' },
  { ar: 'بدر', en: 'Badr' },
  { ar: 'العزيزية', en: 'Al-Aziziyah' },
  { ar: 'الدار البيضاء', en: 'Al-Dar Al-Baida' },
  { ar: 'النسيم', en: 'Al-Naseem' },
  { ar: 'ظهرة لبن', en: 'Dhahrat Laban' },
  { ar: 'طويق', en: 'Tuwaiq' },
  { ar: 'الوادي', en: 'Al-Wadi' },
  { ar: 'غرناطة', en: 'Ghirnatah' },
  { ar: 'القدس', en: 'Al-Quds' },
  { ar: 'الريان', en: 'Al-Rayan' },
  { ar: 'المونسية', en: 'Al-Mounisiyah' },
  { ar: 'الرمال', en: 'Al-Rimal' },
  { ar: 'أشبيلية', en: 'Ishbiliyah' },
  { ar: 'الخليج', en: 'Al-Khaleej' },
  { ar: 'النخيل', en: 'Al-Nakheel' },
  { ar: 'الواحة', en: 'Al-Waha' }
];
